#!/usr/bin/env bash
# Mishi landing — web font pipeline (Phase 0).
#
# Sources the SAME baked static instances the app uses
# (mishi-mobile/assets/fonts, produced by bake-fonts.sh — axes already
# baked, zero variable fonts). Subsets to FR+EN glyphs, converts to
# woff2, verifies no fvar table survives, and emits @font-face CSS with
# metric-matched fallbacks (Georgia for Fraunces, Arial for Instrument
# Sans) so font swap causes zero CLS.
#
#   npm run subset:fonts
set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$DIR/../mishi-mobile/assets/fonts"
OUT="$DIR/public/fonts"
CSS_OUT="$DIR/src/styles/fonts.generated.css"
mkdir -p "$OUT" "$DIR/src/styles"

WORK=$(mktemp -d)
python3 -m venv "$WORK/venv"
"$WORK/venv/bin/pip" -q install fonttools brotli
PY="$WORK/venv/bin/python3"
SUBSET="$WORK/venv/bin/pyftsubset"

# Google "latin" range + U+0178 (Ÿ): covers FR (é è ê ë à â ç î ï ô œ ù û ü ÿ « » €)
# and EN. FCFA prices are ASCII digits — tabular figures come from the tnum
# feature, kept via --layout-features='*'.
UNICODES="U+0000-00FF,U+0131,U+0152-0153,U+0178,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2212,U+2215,U+FEFF,U+FFFD"

# family file weight — weight matches the baked wght axis value.
FONTS=(
  "Fraunces-DisplayHero Fraunces-DisplayHero.ttf 560"
  "Fraunces-DisplayTitle Fraunces-DisplayTitle.ttf 580"
  "Fraunces-DisplaySmall Fraunces-DisplaySmall.ttf 600"
  "InstrumentSans-Regular InstrumentSans-Regular.ttf 400"
  "InstrumentSans-Medium InstrumentSans-Medium.ttf 500"
  "InstrumentSans-SemiBold InstrumentSans-SemiBold.ttf 600"
)

echo "== SUBSET REPORT =="
for entry in "${FONTS[@]}"; do
  read -r family file weight <<<"$entry"
  in="$SRC/$file"
  out="$OUT/${family}.woff2"
  "$SUBSET" "$in" \
    --unicodes="$UNICODES" \
    --layout-features='*' \
    --flavor=woff2 \
    --output-file="$out" \
    --drop-tables+=DSIG \
    --no-hinting --desubroutinize
  before=$(stat -f%z "$in")
  after=$(stat -f%z "$out")
  echo "$family: $before B (ttf) -> $after B (woff2 subset)"
done

echo
echo "== VARIABLE-AXIS + FEATURE VERIFICATION =="
"$PY" - "$OUT" <<'PYEOF'
import sys, glob
from fontTools.ttLib import TTFont

ok = True
for path in sorted(glob.glob(sys.argv[1] + "/*.woff2")):
    f = TTFont(path)
    has_fvar = "fvar" in f
    feats = set()
    if "GSUB" in f and f["GSUB"].table.FeatureList:
        feats = {r.FeatureTag for r in f["GSUB"].table.FeatureList.FeatureRecord}
    glyphs = f["maxp"].numGlyphs
    name = path.split("/")[-1]
    print(f"{name}: fvar={'PRESENT (FAIL)' if has_fvar else 'absent (ok)'} "
          f"glyphs={glyphs} tnum={'yes' if 'tnum' in feats else 'NO'}")
    if has_fvar:
        ok = False
sys.exit(0 if ok else 1)
PYEOF

echo
echo "== METRIC-MATCHED FALLBACKS -> $CSS_OUT =="
"$PY" - "$OUT" "$CSS_OUT" <<'PYEOF'
import sys
from fontTools.ttLib import TTFont

out_dir, css_path = sys.argv[1], sys.argv[2]

FALLBACKS = {
    "Georgia": "/System/Library/Fonts/Supplemental/Georgia.ttf",
    "Arial": "/System/Library/Fonts/Supplemental/Arial.ttf",
}
FONTS = [
    ("Fraunces-DisplayHero", 560, "Georgia"),
    ("Fraunces-DisplayTitle", 580, "Georgia"),
    ("Fraunces-DisplaySmall", 600, "Georgia"),
    ("InstrumentSans-Regular", 400, "Arial"),
    ("InstrumentSans-Medium", 500, "Arial"),
    ("InstrumentSans-SemiBold", 600, "Arial"),
]

# en-US letter frequencies incl. space (capsize's xWidthAvg method) — a
# consistent basis across fonts, unlike OS/2 xAvgCharWidth which older
# fonts (Arial, Georgia) compute differently than modern ones.
FREQ = {
    "a": 0.0668, "b": 0.0122, "c": 0.0228, "d": 0.0348, "e": 0.1039,
    "f": 0.0182, "g": 0.0165, "h": 0.0499, "i": 0.0570, "j": 0.0013,
    "k": 0.0063, "l": 0.0329, "m": 0.0197, "n": 0.0552, "o": 0.0614,
    "p": 0.0158, "q": 0.0008, "r": 0.0489, "s": 0.0518, "t": 0.0741,
    "u": 0.0226, "v": 0.0081, "w": 0.0193, "x": 0.0012, "y": 0.0162,
    "z": 0.0006, " ": 0.1832,
}

def metrics(font):
    upm = font["head"].unitsPerEm
    hhea = font["hhea"]
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    avg = sum(hmtx[cmap[ord(ch)]][0] * w for ch, w in FREQ.items()) / sum(FREQ.values())
    return upm, hhea.ascent, abs(hhea.descent), hhea.lineGap, avg

fb_metrics = {name: metrics(TTFont(path)) for name, path in FALLBACKS.items()}

css = ["/* GENERATED by scripts/subset-fonts.sh — do not edit by hand. */\n"]
report = []
for family, weight, fb in FONTS:
    upm, asc, desc, gap, avg = metrics(TTFont(f"{out_dir}/{family}.woff2"))
    fb_upm, _, _, _, fb_avg = fb_metrics[fb]
    size_adjust = (avg / upm) / (fb_avg / fb_upm)
    css.append(f"""@font-face {{
  font-family: '{family}';
  src: url('/fonts/{family}.woff2') format('woff2');
  font-weight: {weight};
  font-style: normal;
  font-display: swap;
}}
@font-face {{
  font-family: '{family} Fallback';
  src: local('{fb}');
  size-adjust: {size_adjust * 100:.4f}%;
  ascent-override: {asc / upm / size_adjust * 100:.4f}%;
  descent-override: {desc / upm / size_adjust * 100:.4f}%;
  line-gap-override: {gap / upm / size_adjust * 100:.4f}%;
}}
""")
    report.append(f"{family}: fallback={fb} size-adjust={size_adjust*100:.2f}% "
                  f"ascent={asc/upm/size_adjust*100:.2f}% descent={desc/upm/size_adjust*100:.2f}%")

with open(css_path, "w") as f:
    f.write("\n".join(css))
print("\n".join(report))
PYEOF

echo
echo "Done. woff2 in $OUT, CSS in $CSS_OUT"
