// Semantic asset manifest — every landing visual, mapped role → repo path.
// Discovered paths only (audit of 2026-07-17); never invent filenames here.
// The illustrated-menu set (DL61) all carry genuine alpha (verified:
// alphaMin=0 / alphaMax=255 via sharp — no baked checkerboards).

export const landingAssets = {
  // Act 0 — the restaurant world (1672×941 master; responsive variants
  // generated by scripts/optimize-hero.mjs)
  heroRestaurant: {
    avif: ['/hero/hero-800.avif', '/hero/hero-1200.avif', '/hero/hero-1672.avif'],
    webp: ['/hero/hero-800.webp', '/hero/hero-1200.webp', '/hero/hero-1672.webp'],
    width: 1672,
    height: 941,
  },

  // Act 0→1 handoff — the isolated three-fold menu (577×433, transparent)
  heroMenuIsolated: '/menu.png',

  // Act 1 — the five separated paper panels (transparent PNGs)
  menuPanels: {
    farLeft: '/mishi-menu-panel-far-left.png', // 681×1176
    left: '/mishi-menu-panel-left.png', // 667×1191
    center: '/mishi-menu-panel-center.png', // 889×1264
    right: '/mishi-menu-panel-right.png', // 668×1232
    farRight: '/mishi-menu-panel-far-right.png', // 815×1287
  },

  // Act 1 collapse — the flattened five-panel strip (1870×671, transparent)
  menuFlat: '/mishi-menu-five-panel-flat.png',

  // Act 2 — iPhone 17 Pro Max GLB (355 KB, uncompressed; screens blank for now)
  phoneModel: '/3D/iphone_17_pro_max.glb',
  // Act 3 — Draco GLB (pipeline: scripts/optimize-glb.ts; 173 KB)
  plateModel: '/3D/plate.draco.glb',
} as const;

// Where the menu sits INSIDE the hero illustration, as fractions of the
// 1672×941 image (measured from the master, 2026-07-17). The Act 0→1
// handoff positions the isolated menu overlay on top of this region under
// the hero <img>'s object-cover/object-bottom crop (chaos/heroMenu.ts does
// the cover math). Tune here, verify with ?motionDebug=1.
export const HERO_MENU_REGION = {
  x: 0.135, // left edge of the open menu's paper
  y: 0.48, // top edge (the raised spine)
  w: 0.75,
  h: 0.52, // runs to the bottom of the frame (the diner's hand holds it)
} as const;

// The isolated menu asset is a THREE-fold; the menu drawn in the hero is a
// two-panel spread. Registration maps the asset's center+right panels onto
// the hero's two panels — the left panel reads as the fold that opens
// during the lift. Fractions of the 577px asset width.
export const ISOLATED_MENU_MAP = {
  centerFoldX: 0.3, // asset x-fraction that lands on the hero menu's left edge
} as const;
